[
	"absinthe",
	"apple cider",
	"apple pie",
	"baklava",
	"beer cheese",
	"belgian chocolate",
	"black tea",
	"brick oven pizza",
	"brie cheese",
	"brownie",
	"bruschetta",
	"bubble tea",
	"burritos",
	"cajun fries",
	"calzone",
	"cheddar soup",
	"cheese fondue",
	"cheesecake",
	"coffee",
	"cornbread",
	"cotton candy",
	"croissant",
	"cuba libre",
	"dark beer",
	"donuts",
	"enchilada",
	"enchiladas suizas",
	"fajitas",
	"falafel",
	"frappé",
	"french fry",
	"fried pickles",
	"frozen margarita",
	"frozen yogurt",
	"gimlet",
	"ginger ale",
	"goat cheese",
	"greek yoghurt",
	"grilled cheese sandwich",
	"guacamole",
	"jalapeño",
	"latte",
	"lemonade",
	"mac & cheese",
	"mango",
	"mango lassi",
	"margaritas",
	"matzah ball soup",
	"microbrew beers",
	"milkshake",
	"mint tea",
	"miso soup",
	"mojito",
	"mozarella sticks",
	"naan",
	"nachos",
	"noodle soup",
	"onion rings",
	"orange juice",
	"panini",
	"pizza",
	"quinoa",
	"ramen",
	"red velvet cake",
	"red velvet cheescake",
	"red wine",
	"ricotta cheese",
	"root beer",
	"sandwich",
	"single origin coffee",
	"smoothie",
	"souvlaki",
	"stromboli",
	"sushi",
	"tea",
	"tempura",
	"thin crust pizza",
	"tiramisu",
	"tzatziki",
	"watermelon",
	"whiskey",
	"yogurt",
	"fondue",
	"red curry",
	"croquette",
	"masala",
	"gyoza",
	"yellow curry",
	"macchiato",
	"crêpe",
	"waffle",
	"sauerkraut",
	"potato salad",
	"lassi",
	"chai latte",
	"sangira",
	"pierogi",
	"massaman curry",
	"sweet potato fries",
	"toffee pudding",
	"lentil soup",
	"shawarma",
	"flan",
	"kale",
	"huevos rancheros",
	"crème brûlée",
	"poached egg",
	"butterscotch",
	"pecan pie",
	"truffel",
	"mimosa",
	"daiquiri",
	"avocado",
	"tomato soup",
	"gnocchi",
	"tequila",
	"tofu",
	"bread pudding",
	"dumplings",
	"caramel",
	"eggnog",
	"lychee",
	"ginger beer",
	"broccoli cheddar soup",
	"quesadillas",
	"lava cake",
	"popcorn",
	"pineapple",
	"dim sum",
	"banana bread",
	"tortilla soup",
	"pretzels",
	"chimichanga",
	"matzah ball",
	"mai tai",
	"challah",
	"paella",
	"mashed potato",
	"feta cheese",
	"hummus",
	"green tea",
	"chai",
	"hot sake",
	"pad thai",
	"carrot cake",
	"samosa",
	"artichoke",
	"mushroom risotto",
	"risotto",
	"halloumi cheese",
	"smoked tofu",
	"truffle oil",
	"edamame",
	"omlette",
	"pumpkin soup",
	"soba",
	"coconut milk"
];
