[
	"absinthe",
	"apple cider",
	"apple pie",
	"baklava",
	"beer cheese",
	"belgian chocolate",
	"black tea",
	"brick oven pizza",
	"brie cheese",
	"brownie",
	"bruschetta",
	"bubble tea",
	"burritos",
	"cajun fries",
	"calzone",
	"cheddar soup",
	"cheese fondue",
	"cheesecake",
	"coffee",
	"cornbread",
	"cotton candy",
	"croissant",
	"cuba libre",
	"dark beer",
	"donuts",
	"enchilada",
	"enchiladas suizas",
	"fajitas",
	"falafel",
	"frappé",
	"french fry",
	"fried cucumber",
	"frozen margarita",
	"frozen yogurt",
	"gimlet",
	"ginger ale",
	"goat cheese",
	"greek yoghurt",
	"grilled cheese sandwich",
	"guacamole",
	"gyros",
	"jalapeño",
	"kebab",
	"latte",
	"lemonade",
	"mac & cheese",
	"mango",
	"mango lassi",
	"margaritas",
	"matzah ball soup",
	"mezcal",
	"microbrew beers",
	"milkshake",
	"mint tea",
	"miso soup",
	"mojito",
	"mozarella sticks",
	"mulled wine",
	"naan",
	"nachos",
	"noodle soup",
	"onion rings",
	"orange juice",
	"panini",
	"pasta bolognese",
	"philly cheesesteak",
	"pho",
	"pizza",
	"quinoa",
	"ramen",
	"red velvet cake",
	"red velvet cheescake",
	"red wine",
	"ricotta cheese",
	"root beer",
	"sandwich",
	"single origin coffee",
	"smoothie",
	"souvlaki",
	"stromboli",
	"sushi",
	"tartare",
	"tea",
	"tempura",
	"thin crust pizza",
	"tiramisu",
	"tzatziki",
	"watermelon",
	"whiskey",
	"yogurt"
];
